### ISSUE TITLE
error when I run the command ./uniquid build [SOLVED]

### ISSUE THREAD

**Issue by serenaB87** [uniquid/dev-in-a-box#10]
Good morning,
I downloaded the dev-in-a-box on a linux machine with proxy (set globally).
When executing the ./uniquid build command, when the RUN npm install step is executed, I have the following error:

npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to https://registry.npmjs.org/express failed, reason: connect ECONNREFUSED 104.18.96.96:443
npm ERR!     at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)
npm ERR!     at emitOne (events.js:116:13)
npm ERR!     at ClientRequest.emit (events.js:211:7)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:387:9)
npm ERR!     at emitOne (events.js:116:13)
npm ERR!     at TLSSocket.emit (events.js:211:7)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:64:8)
npm ERR!     at _combinedTickCallback (internal/process/next_tick.js:138:11)
npm ERR!     at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR!  { FetchError: request to https://registry.npmjs.org/express failed, reason: connect ECONNREFUSED 104.18.96.96:443
npm ERR!     at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)
npm ERR!     at emitOne (events.js:116:13)
npm ERR!     at ClientRequest.emit (events.js:211:7)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:387:9)
npm ERR!     at emitOne (events.js:116:13)
npm ERR!     at TLSSocket.emit (events.js:211:7)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:64:8)
npm ERR!     at _combinedTickCallback (internal/process/next_tick.js:138:11)
npm ERR!     at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR!   message: 'request to https://registry.npmjs.org/express failed, reason: connect ECONNREFUSED 104.18.96.96:443',
npm ERR!   type: 'system',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   stack: 'FetchError: request to https://registry.npmjs.org/express failed, reason: connect ECONNREFUSED 104.18.96.96:443\n    at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)\n    at emitOne (events.js:116:13)\n    at ClientRequest.emit (events.js:211:7)\n    at TLSSocket.socketErrorListener (_http_client.js:387:9)\n    at emitOne (events.js:116:13)\n    at TLSSocket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)',
npm ERR!   parent: 'legatus' }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-06T08_44_06_667Z-debug.log
ERROR: Service 'legatus' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 1

I have already executed the following commands to set the proxy and the registry also on the /.npmrc file:
npm config set proxy myproxy:port
npm config set https-proxy myproxy:port
npm config set registry http://registry.npmjs.org/

but I still have the same error.
I installed on the machine npm v3.5.2, node v4.2.6 and Docker version 18.03.0-ce, build 0520e24.
Can you help me?
Thanks so much

**Comment by aleclofabbro** [comment]
ciao @serenaB87, 
please use english to let issues be mostly accessible  

I assume you ran those commands (`npm config ...`) on your machine, so they did not affect the containers you were building.
the current version of dev-in-a-box does not provide a proxy configuration for npm.

you could try editing the `dev-in-a-box/legatus/dockerfile` file by inserting those config commands (adding the prefix `RUN`) before `RUN npm install` obtaining:   
```
###
RUN npm config set proxy http://10.10.200.3:3128 
RUN npm config set https-proxy http://10.10.200.3:3128
RUN npm config set registry http://registry.npmjs.org/
RUN npm install
###
```
if your configs are correct and enough, that should work   

please followup with results for this workaround

**Comment by serenaB87** [comment]
Hello,
I have modified the request in English. 
Thank you, your solution worked for me.
I'm going to close the issue.
Thanks again
