### ISSUE TITLE
[SOLVED] no way to login to orchestrator web interface through QR and app

### ISSUE THREAD

**Issue by giovannicandotti** [uniquid/dev-in-a-box#12]
Hi,
I'm no longer able to login to the orchestrator web interface through the mobile app, by dev-in-a-box.
So I restarted all components, and reinstalled the app.

**No way to login through QR code.**

I scan the code, "registering orchestrator" popup for a short moment, and then "Something went wrong during communication"

**Comment by Beatriz84** [comment]
Hi Giovanni,
are the web interface and android phone on the same subnet?

**Comment by giovannicandotti** [comment]
Hi Beatriz84,
Yes, sure

I tried "localhost:8081", "<IP_address>:8081": no way
I guess there was a trick to have this working

**Comment by Beatriz84** [comment]
please check if all the components are up&running
`./uniquid log`

**Comment by giovannicandotti** [comment]
all is ok on log side
when I start with "./uniquid start <ip_address>", all is working fine (I get 4 green "done") too

**Comment by giovannicandotti** [comment]
from "./uniquid log"

Attaching to uniquid_imprinter_1, uniquid_mqtt_1, uniquid_registry_1, uniquid_dashboard_1, uniquid_legatus_1
mqtt_1       | 1535113135: mosquitto version 1.4.12 (build date 2017-06-01 13:03:46+0000) starting
mqtt_1       | 1535113135: Config loaded from /mosquitto/config/mosquitto.conf.
mqtt_1       | 1535113135: Opening ipv4 listen socket on port 1883.
mqtt_1       | 1535113135: Opening ipv6 listen socket on port 1883.
mqtt_1       | 1535113135: Opening websockets listen socket on port 1884.
mqtt_1       | 1535113137: New connection from 172.18.0.6 on port 1883.
mqtt_1       | 1535113137: New connection from 172.18.0.6 on port 1883.
mqtt_1       | 1535113137: New client connected from 172.18.0.6 as ac12000694305b7ff7b1 (c1, k30).
mqtt_1       | 1535113137: New client connected from 172.18.0.6 as ac120006942e5b7ff7b1 (c1, k30).
mqtt_1       | 1535116192: Error in poll: Interrupted system call.
mqtt_1       | 1535116192: mosquitto version 1.4.12 terminating
mqtt_1       | 1535116243: mosquitto version 1.4.12 (build date 2017-06-01 13:03:46+0000) starting
mqtt_1       | 1535116243: Config loaded from /mosquitto/config/mosquitto.conf.
mqtt_1       | 1535116243: Opening ipv4 listen socket on port 1883.
mqtt_1       | 1535116243: Opening ipv6 listen socket on port 1883.
mqtt_1       | 1535116243: Opening websockets listen socket on port 1884.
mqtt_1       | 1535116245: New connection from 172.18.0.6 on port 1883.
mqtt_1       | 1535116245: New connection from 172.18.0.6 on port 1883.
mqtt_1       | 1535116245: New client connected from 172.18.0.6 as ac120006ce3a5b8003d5 (c1, k30).
mqtt_1       | 1535116245: New client connected from 172.18.0.6 as ac120006ce385b8003d5 (c1, k30).
legatus_1    | > node index.js
legatus_1    | 
legatus_1    | listening on *:3000
legatus_1    | a machine connected Oiy7RDQgtBpvx23zAAAA
legatus_1    | a machine connected s4X4DzLqkupSitMBAAAB
legatus_1    | 55f81340-a79f-11e8-9778-374c9a87bcae
legatus_1    | a machine connected L6ebLEFWceZIpgHxAAAC
legatus_1    | 8b7e29a0-a79f-11e8-a9f7-a927649479b6
legatus_1    | a machine connected Nwyop6itY_7hGlS2AAAD
legatus_1    | a93595a0-a79f-11e8-99ce-9f0b0de39adf
legatus_1    | a machine connected fVXZJ3zSmOC9vvwUAAAE
legatus_1    | f218cb70-a79f-11e8-9119-471c429771f6
legatus_1    | a machine connected 3OSoM7DUIsvdBt-kAAAF
legatus_1    | 43d51a20-a7a2-11e8-b325-4187e4a06b1a
legatus_1    | a machine connected Qf1wtBnvTpcX47YtAAAG
legatus_1    | 2520f740-a7a5-11e8-b4ea-af50ec510b26
legatus_1    | a machine connected tpvUgltVFfIK5gITAAAH
legatus_1    | 28bcbba0-a7a5-11e8-9708-8d41eb913f02
legatus_1    | a machine connected pPQSRAx-9gV27qzcAAAI
legatus_1    | 25b24fe0-a7a7-11e8-b0a6-bd3d7aeece42
dashboard_1  | 172.18.0.1 - - [24/Aug/2018:13:53:56 +0000] "GET /configs/ctrBitmask.json HTTP/1.1" 200 590 "http://127.0.0.1:8081/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
dashboard_1  | 172.18.0.1 - - [24/Aug/2018:13:53:56 +0000] "GET /configs/services.json HTTP/1.1" 200 265 "http://127.0.0.1:8081/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
dashboard_1  | 172.18.0.1 - - [24/Aug/2018:13:53:56 +0000] "GET /configs/tabacchi.json HTTP/1.1" 200 529 "http://127.0.0.1:8081/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
dashboard_1  | 172.18.0.1 - - [24/Aug/2018:13:53:57 +0000] "GET /static/media/logo.c9091006.svg HTTP/1.1" 200 7759 "http://127.0.0.1:8081/static/css/main.5fe38faa.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
dashboard_1  | 172.18.0.1 - - [24/Aug/2018:13:53:57 +0000] "GET /static/media/uniquid.8f4340a2.ttf HTTP/1.1" 200 11796 "http://127.0.0.1:8081/static/css/main.5fe38faa.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
dashboard_1  | 172.18.0.1 - - [24/Aug/2018:13:54:01 +0000] "GET / HTTP/1.1" 200 529 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
dashboard_1  | 172.18.0.1 - - [24/Aug/2018:13:54:01 +0000] "GET /public/style.css HTTP/1.1" 200 175114 "http://localhost:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
dashboard_1  | 172.18.0.1 - - [24/Aug/2018:13:54:01 +0000] "GET /static/css/main.5fe38faa.css HTTP/1.1" 200 175122 "http://localhost:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
dashboard_1  | 172.18.0.1 - - [24/Aug/2018:13:54:01 +0000] "GET /static/js/main.a213655d.js HTTP/1.1" 200 1498890 "http://localhost:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
dashboard_1  | 172.18.0.1 - - [24/Aug/2018:13:54:01 +0000] "GET /configs/ctrBitmask.json HTTP/1.1" 200 590 "http://localhost:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
dashboard_1  | 172.18.0.1 - - [24/Aug/2018:13:54:01 +0000] "GET /configs/services.json HTTP/1.1" 200 265 "http://localhost:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
dashboard_1  | 172.18.0.1 - - [24/Aug/2018:13:54:01 +0000] "GET /configs/tabacchi.json HTTP/1.1" 200 529 "http://localhost:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
dashboard_1  | 172.18.0.1 - - [24/Aug/2018:13:54:02 +0000] "GET /static/media/logo_black.fc9da88d.svg HTTP/1.1" 200 7190 "http://localhost:8081/static/css/main.5fe38faa.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
dashboard_1  | 172.18.0.1 - - [24/Aug/2018:13:54:02 +0000] "GET /static/media/shield2.1ed21425.svg HTTP/1.1" 200 279 "http://localhost:8081/static/css/main.5fe38faa.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
dashboard_1  | 172.18.0.1 - - [24/Aug/2018:13:54:02 +0000] "GET /static/media/list.156e6dca.svg HTTP/1.1" 200 473 "http://localhost:8081/static/css/main.5fe38faa.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
dashboard_1  | 172.18.0.1 - - [24/Aug/2018:13:54:02 +0000] "GET /static/media/profile.9fbb8ca0.jpg HTTP/1.1" 200 15023 "http://localhost:8081/static/css/main.5fe38faa.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
dashboard_1  | 172.18.0.1 - - [24/Aug/2018:13:54:02 +0000] "GET /static/media/target.10c63764.svg HTTP/1.1" 200 336 "http://localhost:8081/static/css/main.5fe38faa.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
dashboard_1  | 172.18.0.1 - - [24/Aug/2018:13:54:02 +0000] "GET /static/media/uniquid.8f4340a2.ttf HTTP/1.1" 200 11796 "http://localhost:8081/static/css/main.5fe38faa.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
dashboard_1  | 172.18.0.1 - - [24/Aug/2018:13:54:04 +0000] "GET /static/media/logo.c9091006.svg HTTP/1.1" 200 7759 "http://localhost:8081/static/css/main.5fe38faa.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
dashboard_1  | 172.18.0.1 - - [24/Aug/2018:14:08:16 +0000] "GET /configs/services.json HTTP/1.1" 200 265 "http://172.20.10.6:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-"
registry_1   | [main] INFO com.uniquid.registry.Main - Found empty database! Creating needed tables
registry_1   | [main] INFO org.eclipse.jetty.util.log - Logging initialized @818ms
registry_1   | [main] INFO com.uniquid.registry.Main - Base URI: jar:file:/registry-0.1-RC1-SNAPSHOT-jar-with-dependencies.jar!/webroot/
registry_1   | [main] INFO org.eclipse.jetty.server.Server - jetty-9.3.z-SNAPSHOT
registry_1   | [main] WARN org.eclipse.jetty.webapp.StandardDescriptorProcessor - Duplicate mapping from / to default
registry_1   | [main] WARN org.eclipse.jetty.webapp.StandardDescriptorProcessor - Duplicate mapping from *.jsp to jsp
registry_1   | [main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.w.WebAppContext@536aaa8d{/,jar:file:/registry-0.1-RC1-SNAPSHOT-jar-with-dependencies.jar!/webroot/,AVAILABLE}
registry_1   | [main] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@46995b62{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
registry_1   | [main] INFO org.eclipse.jetty.server.Server - Started @1174ms
registry_1   | [main] INFO com.uniquid.registry.Main - Server URI: http://localhost:8080/
registry_1   | [main] INFO com.uniquid.settings.model.AbstractSettings - analyzing class for settings: class com.uniquid.registry.utils.RegistrySettings
registry_1   | [main] INFO org.eclipse.jetty.util.log - Logging initialized @632ms
registry_1   | [main] INFO com.uniquid.registry.Main - Base URI: jar:file:/registry-0.1-RC1-SNAPSHOT-jar-with-dependencies.jar!/webroot/
registry_1   | [main] INFO org.eclipse.jetty.server.Server - jetty-9.3.z-SNAPSHOT
registry_1   | [main] WARN org.eclipse.jetty.webapp.StandardDescriptorProcessor - Duplicate mapping from / to default
registry_1   | [main] WARN org.eclipse.jetty.webapp.StandardDescriptorProcessor - Duplicate mapping from *.jsp to jsp
registry_1   | [main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.w.WebAppContext@536aaa8d{/,jar:file:/registry-0.1-RC1-SNAPSHOT-jar-with-dependencies.jar!/webroot/,AVAILABLE}
registry_1   | [main] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@69a3d1d{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
registry_1   | [main] INFO org.eclipse.jetty.server.Server - Started @1013ms
registry_1   | [main] INFO com.uniquid.registry.Main - Server URI: http://localhost:8080/

**Comment by Beatriz84** [comment]
I can't see the "imprinter" service in this log... please check it via browser on
`http://localhost:8090`

**Comment by giovannicandotti** [comment]
<img width="1199" alt="screen shot 2018-08-24 at 16 13 02" src="https://user-images.githubusercontent.com/16572107/44589364-b2c6e380-a7b8-11e8-809f-50c2ae66b35f.png">

**Comment by giovannicandotti** [comment]
if it can help the analysis, I had the system running, more than one month ago.

Today it was no longer available.
So I rebuilt, and restarted the same way as one month ago.

**Comment by Beatriz84** [comment]
I'm sorry Giovanni, I've noticed just now your correction at second post, can you please explain me this? 

> I tried "localhost:8081", "<IP_address>:8081": no way
> I guess there was a trick to have this working

**Comment by giovannicandotti** [comment]
Problem solved: the smartphone hotspot I used was not routing properly (I guess), with a normal wireless network it works like a charm
