### ISSUE TITLE
Feature? spinner su interfaccia orchestratore

### ISSUE THREAD

**Issue by enricuez92** [uniquid/dev-in-a-box#3]
Durante il mining non si capisce se il processo è in corso, sarebbe ideale uno spinner loading così non clicco continuamente il tasto.

**Comment by g0dz1ll4** [comment]
Thanks @enricuez92 for your feedback. 
Please can you provide a description in English to keep understandable for all ? 
Anyway what branch you're using?

**Comment by g0dz1ll4** [comment]
Dear @enricuez92  I've understood your issue. 

The mining operation on dashboard is just a Call for Action. No result messages are dispatched from blockchain to dashboard.

The button is a kind of help for the developer so  you don't need wait the blockchain mining interval (on the testate or main net is possible that you must wait several minutes between two blocks).

When you click on Mine button the operation went notified on the Notification Area.

Remain that you must wait the time for mining propagation on blockchain and dashboard refresh statuses.
