### ISSUE TITLE
Communication between dev-in-a-box and Tank Manager

### ISSUE THREAD

**Issue by MicheleFoderaro** [uniquid/dev-in-a-box#8]
Hi

I have completed the installation and configuration of "dev-in-a-box" system. After, I have installed the app "Tank Manager" with default settings. But I don't know how linked these two components together, for now they don't communicate between each other. There is documentation about that or someone can help me?
 
Thanks in advance

**Comment by marco-palumbi** [comment]
please give a look at tank-c.ini file in the bin directory. 
Edit it according whit your address. just take in account that when you run make on the tank-c project, it will copy the default tank-c.ini from the sources to the bin dir...

**Comment by aleclofabbro** [comment]
TankManager default settings are not suitable for a local dev-in-a-box.
in TankManager app: 
- enter setting page : tap `menu -> settings`

Change broker endpoint:
- enter brokers page : tap `menu -> Manage brokers`
- click `(+)` to add a new broker endpoint an type in `tcp://<YOUR_LOCAL_DEVBOX_IP>:1883`
- back to settings page tap `broker` field and select the newly added one

Change Registry endpoint:
- enter Registry urls page : tap `menu -> Manage registry urls`
- click `(+)` to add a new broker endpoint an type in `http://<YOUR_LOCAL_DEVBOX_IP>:8080`
- back to settings page tap `Registry URL` field and select the newly added one

remember `YOUR_LOCAL_DEVBOX_IP` is an accessible address for the TankManager and Orchestrator app

**Comment by MicheleFoderaro** [comment]
Thanks for your answers. 
@marco-palumbi I don't use tank-c but only tanks in java, and in Java directory there isn't a file .ini, perhaps I should edit config.properties file? 
So default settings aren't ok, now I have tried to put a local ip address such as 172.17.0.1 but it doesn't work (obviously I have update the tank manager app with the IP). Which ip address should I choose? 

Thanks in advance

**Comment by marco-palumbi** [comment]
use your ip address for broker and registry and default for blockchain peers
mqtt.broker=tcp\://YourIPaddress\:1883
bc.peers=52.225.217.168;52.167.211.151
registry.url=http\://YourIPaddress:8080

**Comment by aleclofabbro** [comment]
@MicheleFoderaro the `yourIP` we are mentioning is the IP of the machine where the dev-in-a-box is currently running (likely your own PC)  
UniquidNodes (such as TankManager app, tanks, Orchestrator app, ...) need to point to services exposed on the machine running dev-in-a-box ( see  https://github.com/uniquid/dev-in-a-box#check-system-components )
